name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Updated to use the v2 version

    - name: Run commands and build the Docker image
      run: |
        cd docker# Replace with your directory
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
